setup: 
	clear
	sudo python3 setup.py install
.PHONY: all test clean

clean:
	rm -rf build/ __pycache__ .setup.py.un~ .Makefile.un~ .Makefile.swp
	rm .main.py.swp
	rm .cnetwork.c.un~
	rm ..gitignore.un~
	rm .main.py.un~
